---
kind: Service
apiVersion: v1
metadata:
  name: demosvc
spec:
  selector:
    app: demoapp
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8081
      # Port to forward to inside the pod
      targetPort: 8080
      # Port accessible outside cluster
      # nodePort: 30002
  type: LoadBalancer


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-deployment
  labels:
    app: demoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: demoapp
        image: yablokov/demo
        ports:
        - containerPort: 8080

